# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carre.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carre_Dialog(object):
    def setupUi(self, Carre_Dialog):
        Carre_Dialog.setObjectName("Carre_Dialog")
        Carre_Dialog.resize(400, 400)
        Carre_Dialog.setMinimumSize(QtCore.QSize(400, 400))
        Carre_Dialog.setMaximumSize(QtCore.QSize(400, 400))
        Carre_Dialog.setModal(True)
        self.resultat = QtWidgets.QTextEdit(Carre_Dialog)
        self.resultat.setEnabled(False)
        self.resultat.setGeometry(QtCore.QRect(50, 10, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.resultat.setFont(font)
        self.resultat.setObjectName("resultat")
        self.btn_valider = QtWidgets.QPushButton(Carre_Dialog)
        self.btn_valider.setGeometry(QtCore.QRect(50, 180, 131, 41))
        self.btn_valider.setStyleSheet("background-color: rgb(0, 141, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btn_valider.setObjectName("btn_valider")
        self.layoutWidget = QtWidgets.QWidget(Carre_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 120, 311, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cote = QtWidgets.QLineEdit(self.layoutWidget)
        self.cote.setObjectName("cote")
        self.horizontalLayout.addWidget(self.cote)

        self.retranslateUi(Carre_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Carre_Dialog)

    def retranslateUi(self, Carre_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Carre_Dialog.setWindowTitle(_translate("Carre_Dialog", "Surface du carre"))
        self.btn_valider.setText(_translate("Carre_Dialog", "Valider"))
        self.label.setText(_translate("Carre_Dialog", "Coté"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Carre_Dialog = QtWidgets.QDialog()
    ui = Ui_Carre_Dialog()
    ui.setupUi(Carre_Dialog)
    Carre_Dialog.show()
    sys.exit(app.exec_())
