# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        MainWindow.setStyleSheet("background-color: rgb(26, 95, 180);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_rectangle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rectangle.setGeometry(QtCore.QRect(80, 90, 221, 61))
        self.btn_rectangle.setStyleSheet("background-color: rgb(0, 141, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btn_rectangle.setObjectName("btn_rectangle")
        self.btn_carre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carre.setGeometry(QtCore.QRect(80, 170, 221, 61))
        self.btn_carre.setStyleSheet("background-color: rgb(0, 141, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btn_carre.setObjectName("btn_carre")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ACCUEIL"))
        self.btn_rectangle.setText(_translate("MainWindow", "Surface du rectangle"))
        self.btn_carre.setText(_translate("MainWindow", "Surface du carre"))
        self.label.setText(_translate("MainWindow", "Choisir une option"))



