# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangle.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rectangle_Dialog(object):
    def setupUi(self, Rectangle_Dialog):
        Rectangle_Dialog.setObjectName("Rectangle_Dialog")
        Rectangle_Dialog.resize(400, 400)
        Rectangle_Dialog.setMinimumSize(QtCore.QSize(400, 400))
        Rectangle_Dialog.setMaximumSize(QtCore.QSize(400, 400))
        Rectangle_Dialog.setModal(True)
        self.resultat = QtWidgets.QTextEdit(Rectangle_Dialog)
        self.resultat.setEnabled(False)
        self.resultat.setGeometry(QtCore.QRect(40, 20, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.resultat.setFont(font)
        self.resultat.setObjectName("resultat")
        self.btn_valider = QtWidgets.QPushButton(Rectangle_Dialog)
        self.btn_valider.setGeometry(QtCore.QRect(40, 230, 131, 41))
        self.btn_valider.setStyleSheet("background-color: rgb(0, 141, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btn_valider.setObjectName("btn_valider")
        self.layoutWidget = QtWidgets.QWidget(Rectangle_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 130, 331, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.longueur = QtWidgets.QLineEdit(self.layoutWidget)
        self.longueur.setObjectName("longueur")
        self.horizontalLayout.addWidget(self.longueur)
        self.layoutWidget1 = QtWidgets.QWidget(Rectangle_Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 180, 331, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.largueur = QtWidgets.QLineEdit(self.layoutWidget1)
        self.largueur.setObjectName("largueur")
        self.horizontalLayout_2.addWidget(self.largueur)

        self.retranslateUi(Rectangle_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Rectangle_Dialog)

    def retranslateUi(self, Rectangle_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Rectangle_Dialog.setWindowTitle(_translate("Rectangle_Dialog", "Surface du rectangle"))
        self.btn_valider.setText(_translate("Rectangle_Dialog", "Valider"))
        self.label.setText(_translate("Rectangle_Dialog", "Longueur"))
        self.label_2.setText(_translate("Rectangle_Dialog", "Largueur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rectangle_Dialog = QtWidgets.QDialog()
    ui = Ui_Rectangle_Dialog()
    ui.setupUi(Rectangle_Dialog)
    Rectangle_Dialog.show()
    sys.exit(app.exec_())
